machinesets:
  infrastructure_id: cluster-0e58-scm6d
  ami_id: ami-010de485a2ee23e5e
  gpus:
    - name: p2-xlarge
      instanceType: p2.xlarge
      zone: us-west-2a
      region: us-west-2
      machineAutoscaler:
        enabled: true
        minReplicas: 0
        maxReplicas: 2
    - name: p2-8xlarge
      instanceType: p2.8xlarge
      zone: us-west-2a
      region: us-west-2
      machineAutoscaler:
        enabled: true
        minReplicas: 0
        maxReplicas: 2
  proactiveAutoscaler:
    - name: m5-large
      instanceType: m5.large
      zone: us-west-2a
      region: us-west-2
      machineAutoscaler:
        enabled: true
        minReplicas: 0
        maxReplicas: 12

