apiVersion: autoscaling.openshift.io/v1beta1
kind: MachineAutoscaler
metadata:
  name: {{ printf "%v-%v-%v" .Values.machineset.infrastructure_id .Values.machineset.g3sxlarge.role .Values.machineset.zone }}
  namespace: openshift-machine-api
spec:
  minReplicas: 0
  maxReplicas: 2
  scaleTargetRef: 
    apiVersion: machine.openshift.io/v1beta1
    kind: MachineSet
    name: {{ printf "%v-%v-%v" .Values.machineset.infrastructure_id .Values.machineset.g3sxlarge.role .Values.machineset.zone }}
