apiVersion: redhatcop.redhat.io/v1alpha1
kind: NodeScalingWatermark
metadata:
  name: proactive-autoscaler3
  namespace: proactive-node-scaling-test2
spec:
  priorityClassName: proactive-node-autoscaling-pods
  watermarkPercentage: 100
  pausePodSize:
    cpu: '1'
    memory: 1280Mi
  nodeSelector:
    node-role.kubernetes.io/proactive-autoscaler: ''
  tolerations:
    - key: node-role.kubernetes.io/proactive-autoscaler
      operator: "Exists"
      effect: "NoSchedule"
