apiVersion: redhatcop.redhat.io/v1alpha1
kind: NodeScalingWatermark
metadata:
  name: proactive-autoscaler
spec:
  priorityClassName: proactive-node-autoscaling-pods
  watermarkPercentage: 20
  pausePodSize:
    cpu: 100m
    memory: 128Mi
  nodeSelector:
    node-role.kubernetes.io/proactive-autoscaler: ''
  tolerations:
    - key: node-role.kubernetes.io/proactive-autoscaler
      operator: "Exists"
      effect: "NoSchedule"
