kind: Namespace
apiVersion: v1
metadata:
  name: proactive-node-scaling-test2
  labels:
    name: proactive-node-scaling-test2
  annotations:
    scheduler.alpha.kubernetes.io/defaultTolerations: |-
      [
        {"operator": "Exists", "effect": "NoSchedule", "key": "node-role.kubernetes.io/{{ .Values.machineset.role }}"},
        {"operator": "Exists", "effect": "NoSchedule", "key": "node-role.kubernetes.io/gpu"}
      ]
    scheduler.alpha.kubernetes.io/tolerationsWhitelist: |-
      [
        {"operator": "Exists", "effect": "NoSchedule", "key": "node-role.kubernetes.io/{{ .Values.machineset.role }}"},
        {"operator": "Exists", "effect": "NoSchedule", "key": "node-role.kubernetes.io/gpu"},
        {"operator": "Exists", "effect": "NoSchedule", "key": "node.kubernetes.io/memory-pressure"},
        {"operator": "Exists", "tolerationSeconds": 300, "effect": "NoExecute", "key": "node.kubernetes.io/unreachable"},
        {"operator": "Exists", "tolerationSeconds": 300, "effect": "NoExecute", "key": "node.kubernetes.io/not-ready"}
      ]
